export const LSF_VOCABULARY = [
  "a priori",
  "abandonner",
  "abbaye",
  "abdiquer",
  "abeille",
  "ablation",
  "abonnement",
  "académie",
  "accident de voiture",
  "accompagner",
  "accompagner (1)",
  "accord",
  "achat",
  "acheter",
  "acide",
  "acoustique",
  "action",
  "adaptation",
  "adhérer",
  "adjuger",
  "administrer",
  "adolescent",
  "adorer",
  "adversaire",
  "affaire",
  "agence",
  "agression",
  "agriculture",
  "Aix",
  "Albi",
  "album de photos",
  "Algérie",
  "Allemagne",
  "aller (1)",
  "aller chercher",
  "amant",
  "ambiance",
  "ambition",
  "ami·e (1)",
  "ami·e·s",
  "amour",
  "analogie",
  "analyse",
  "anatomie",
  "Angers",
  "anniversaire",
  "anonyme",
  "antiquité",
  "aorte",
  "apercevoir",
  "apesanteur",
  "appeler",
  "apporter",
  "apprendre",
  "approcher",
  "appétit",
  "après (1)",
  "après-midi",
  "arbre",
  "archipel",
  "architecte",
  "archives",
  "argenté",
  "arrêter",
  "articulation, os",
  "arts",
  "assemblée nationale",
  "association",
  "assurance",
  "asthme",
  "atome",
  "attendre",
  "attention",
  "attestation",
  "au bord de…",
  "au revoir",
  "Aubagne",
  "audiogramme",
  "audiovisuel",
  "aujourd'hui",
  "Australie",
  "automobile, voiture",
  "autonome",
  "autonomie",
  "autoroute",
  "Autriche",
  "avant",
  "avec",
  "avertir, prévenir",
  "Avignon",
  "avion",
  "avocat",
  "avocat (1)",
  "bac",
  "ballon",
  "banane",
  "banlieue",
  "banque",
  "banque (2)",
  "banquet",
  "baptême",
  "baptême (1)",
  "barbelé",
  "base",
  "bateau",
  "beacoup",
  "beau",
  "beige",
  "Belgique",
  "Biarritz",
  "bible",
  "bibliothèque",
  "bien",
  "bientôt (1)",
  "bilan",
  "bilinguisme",
  "billard",
  "biochimie",
  "biologie",
  "blanc",
  "bleu (1)",
  "bleu marine",
  "blond",
  "blouse",
  "bobine",
  "boeuf",
  "boire",
  "boiter",
  "bon (1)",
  "bon appétit",
  "bonjour",
  "bonjour (1)",
  "bonne journée",
  "bonne soirée",
  "bonsoir",
  "bordeaux",
  "Bordeaux",
  "bouddhisme",
  "boudin",
  "bourgeois",
  "bowling",
  "bracelet",
  "Bretagne",
  "Bruxelles",
  "Brésil",
  "budget",
  "Bulgarie",
  "bureau",
  "bus",
  "bâtiment",
  "bébé",
  "bénéfice",
  "bénévolat",
  "caducée",
  "café",
  "calcul",
  "calendrier",
  "camion",
  "campagne",
  "Canada",
  "canal",
  "canapé",
  "canard",
  "cancer",
  "candidat",
  "canicule",
  "capacité",
  "capitale",
  "capter des mots",
  "car",
  "caractère",
  "carotte",
  "carte d'identité",
  "carême",
  "casser",
  "cassette",
  "catholique",
  "censure",
  "centre ville",
  "cerf",
  "certificat",
  "chaise",
  "Chambéry",
  "champ",
  "champignon",
  "champignon (1)",
  "champion",
  "chance",
  "chance (1)",
  "changer",
  "chapeau",
  "chapeau (1)",
  "charbon",
  "charcutier",
  "chariot",
  "charpente",
  "charpente (1)",
  "chat",
  "chaud",
  "chaussette",
  "chaussette (1)",
  "chaussure",
  "chauve-souris",
  "chemin",
  "chemin (1)",
  "chemise",
  "chercher (3)",
  "chercher les ennuis",
  "chercher quelqu'un de perdu",
  "chien",
  "chimie",
  "Chine",
  "chocolat (1)",
  "chocolatine (pain au chocolat)",
  "châtain",
  "château",
  "chéquier",
  "cinéma",
  "cinéma (1)",
  "circuit",
  "cirque",
  "citoyen",
  "citron",
  "civil",
  "clair",
  "clochard",
  "cloche",
  "clou",
  "clown",
  "clown (1)",
  "clôture",
  "coca",
  "cochon",
  "coco",
  "cocon",
  "code de la route",
  "coffre",
  "coiffure",
  "col",
  "collaboration",
  "collant",
  "collant (vêtement)",
  "collier",
  "colline",
  "collège",
  "collège (1)",
  "colonie",
  "colère",
  "combien ?",
  "comique",
  "comité",
  "commencer",
  "comment ?",
  "comment dire ?",
  "commerce",
  "commission",
  "communauté",
  "communication",
  "communiquer",
  "communisme",
  "comportement",
  "comprendre",
  "compris",
  "compromis",
  "comptabilité",
  "compétant",
  "compétition",
  "comédie",
  "comédien",
  "concentration",
  "concentrer",
  "concept",
  "concombre",
  "concours",
  "concours (1)",
  "concurrence",
  "confiance",
  "configuration",
  "conflit",
  "conférence",
  "conférence pour les entendants",
  "conférence pour les sourds",
  "congrès",
  "connaissance",
  "conscience",
  "conseiller",
  "conseiller (1)",
  "construction navale",
  "conte",
  "content",
  "contrat",
  "convaincre",
  "conversation (discuter)",
  "conversion",
  "convoquer",
  "coq",
  "coquillage",
  "cordonnier",
  "corne",
  "cornichon",
  "corps",
  "correction (corriger)",
  "cotisation",
  "coton",
  "couche",
  "coude",
  "couette",
  "couleur",
  "couloir",
  "coupable",
  "couple",
  "cour",
  "courgette",
  "courir",
  "couronne",
  "cours",
  "course",
  "couscous",
  "couscous (1)",
  "cousin",
  "cousin (1)",
  "couteau",
  "couvercle",
  "couverture",
  "crabe",
  "craie",
  "crampe",
  "cravate",
  "crayon",
  "crevette",
  "crime",
  "critiquer",
  "critiquer (1)",
  "crochet",
  "crocodile",
  "croiser",
  "croissant",
  "croissant (1)",
  "croix",
  "crédit",
  "crêpe",
  "cuir",
  "cuisine",
  "culotte",
  "culture (1)",
  "culture de la terre",
  "curieux",
  "câble",
  "célibataire",
  "dactylologie",
  "Danemark",
  "danser",
  "de (6)",
  "de rien",
  "demain",
  "demander",
  "dentiste",
  "dernière",
  "derrière",
  "dessert",
  "dette",
  "devant",
  "devis",
  "devoir",
  "diabète",
  "dialogue",
  "dialoguer",
  "différent",
  "Dijon",
  "dilatation",
  "diplomatique",
  "diplôme",
  "diplôme (1)",
  "dire (1)",
  "directeur",
  "directeur (1)",
  "discuter (1)",
  "distance",
  "divorce",
  "divorcer",
  "docteur",
  "doctorat en médecine",
  "documentation",
  "dommage",
  "donner, rendre",
  "dormir",
  "doré",
  "dossier",
  "dossier (1)",
  "doyen",
  "drogue",
  "droit",
  "débat",
  "débilité",
  "débit banque",
  "décembre",
  "décentralisation",
  "décision",
  "déclaration (1)",
  "déclaration droits de l'homme",
  "décommander",
  "décompte",
  "décors",
  "découragement",
  "découverte",
  "défaut",
  "défenseur",
  "déficit",
  "dégressif",
  "dégustation",
  "délivrance",
  "déluge",
  "démenagement",
  "démissionner",
  "démocratie",
  "démonstration",
  "département",
  "dépression",
  "député",
  "dérogation",
  "détail",
  "eau",
  "email",
  "emballage",
  "embaucher",
  "embaucher (1)",
  "emplacement",
  "emploi du temps",
  "emprunt",
  "encore",
  "encéphalogramme",
  "endoctriner",
  "enfant",
  "engagement",
  "engrenage",
  "enlèvement",
  "ennemi",
  "enquête",
  "enregistrer",
  "enseigner",
  "enseigner, apprendre",
  "ensemble",
  "entendant",
  "entendre",
  "enthousiasme",
  "entrée",
  "envergure (oiseaux)",
  "envie",
  "envoyer",
  "escargot",
  "Espagne",
  "espérer",
  "essayer",
  "Europe",
  "eux",
  "examen",
  "exemple",
  "exemple (1)",
  "exercice",
  "expert",
  "expliquer",
  "exploit",
  "exportation",
  "expression du visage",
  "expression du visage (1)",
  "expression, mots",
  "expérience",
  "fabrication",
  "facture",
  "faillite",
  "falsifier",
  "famille",
  "fantasme",
  "fascisme",
  "fatigué",
  "faussaire",
  "faxer",
  "femme (1)",
  "femme de ménage",
  "fenêtre",
  "fermé",
  "fier",
  "filet",
  "fille (1)",
  "fille (la)",
  "film",
  "fils",
  "finir",
  "Finlande",
  "fleur",
  "fleuve",
  "foie",
  "foncé",
  "fonder",
  "foot",
  "formateur",
  "formation",
  "formation (1)",
  "forme",
  "forêt",
  "fraise",
  "France",
  "français",
  "français (langue)",
  "frite",
  "froid",
  "fromage",
  "fruit",
  "frère",
  "futur",
  "fédération",
  "félicitation",
  "fête",
  "fêter",
  "Gap",
  "gare",
  "garçon",
  "gentil",
  "girafe",
  "glisser",
  "grammaire",
  "grand (3)",
  "grand-mère",
  "grand-parent",
  "grand-père",
  "grave",
  "gravure",
  "griffe",
  "gris",
  "gronder",
  "gros",
  "Grèce",
  "Guyane",
  "gymnastique",
  "gâteau",
  "géographie",
  "habiter",
  "haine",
  "handicapé",
  "herbe",
  "hier",
  "histoire",
  "histoire (1)",
  "hiver",
  "hiérarchie",
  "Hollande",
  "hommage",
  "homme (1)",
  "homme (2)",
  "Hongrie",
  "honneur",
  "honte",
  "horizon",
  "horticulture",
  "huissier",
  "humour",
  "hypnose",
  "hypocrite",
  "hélicoptère",
  "hémorragie",
  "héritage",
  "hôpital",
  "hôpital (1)",
  "hôtel",
  "I love you",
  "iconique",
  "idéologie",
  "il fait beau",
  "il n'y a personne",
  "il neige",
  "il pleut",
  "il y a du vent",
  "illusion",
  "imiter, copier",
  "immeuble",
  "important",
  "imprimer",
  "impôts",
  "inauguration",
  "Inde",
  "individu",
  "infarctus",
  "infirmière",
  "infirmière (1)",
  "influence",
  "information",
  "informatique",
  "informer",
  "informer (1)",
  "ingénieur",
  "insertion",
  "instituteur, professeur",
  "intelligence",
  "international",
  "Internet",
  "interpréter",
  "interrogation",
  "intervenir",
  "intervenir (1)",
  "interview",
  "intérioriser",
  "invention",
  "inviter",
  "Irlande",
  "Israël",
  "Italie",
  "italien (langue)",
  "j'ai (2)",
  "j'ai le temps",
  "j'ai vu",
  "j'aime",
  "jamais",
  "jambon",
  "Japon",
  "jardinage",
  "jaune",
  "jazz",
  "je connais",
  "je crois",
  "je n'ai pas (2)",
  "je n'ai pas le temps",
  "je n'ai pas vu",
  "je n'aime pas",
  "je ne connais pas",
  "je ne crois pas",
  "je ne peux pas",
  "je ne sais pas",
  "je ne suis pas là",
  "je ne veux pas",
  "je peux",
  "je sais",
  "je suis d'accord",
  "je suis là",
  "je veux",
  "jeu (1)",
  "jeu de cartes",
  "jeune",
  "jeunesse",
  "jouer",
  "journée (1)",
  "jupe",
  "justice",
  "kaki",
  "Kg (kilogramme)",
  "kidnapper",
  "kinésithérapie",
  "kleptomanie",
  "Km (kilomètre)",
  "Kwatt (kilowatt)",
  "la mode",
  "laid",
  "langue",
  "langue (3)",
  "Laos",
  "lapin",
  "leader",
  "lecture (1)",
  "lecture labiale",
  "liaison",
  "libellule",
  "liberté",
  "librairie",
  "libre",
  "licenciement",
  "Lille",
  "Limoges",
  "linguistique",
  "lit",
  "livre",
  "location",
  "loi",
  "LSF",
  "lui, elle",
  "Lyon",
  "légume",
  "ma, mes",
  "machine",
  "madame",
  "mademoiselle",
  "mafia",
  "maintenant",
  "mairie",
  "mairie (1)",
  "maison",
  "majeur",
  "mal-entendant",
  "malade",
  "maladie",
  "maman",
  "manger",
  "manifestation",
  "manteau",
  "marcher",
  "marginal",
  "marier",
  "Marignane",
  "Maroc",
  "marron",
  "Marseille",
  "Marseille (1)",
  "matin",
  "mauvais",
  "maîtresse",
  "media",
  "mensuel",
  "mer",
  "merci",
  "message",
  "messe",
  "mettre (1)",
  "mettre à la porte",
  "Metz",
  "Mexique",
  "microbe",
  "microscope",
  "midi (1)",
  "militaire",
  "mine",
  "minorité",
  "moderne",
  "moi",
  "Monaco",
  "monde",
  "monsieur",
  "montagne",
  "montagne (1)",
  "montgolfière",
  "Montpellier",
  "montre (accessoire)",
  "moquer",
  "moral",
  "mot",
  "moto",
  "mouton",
  "mouvement",
  "Mulhouse",
  "musique",
  "musulman",
  "mutation",
  "mécanique",
  "méchant",
  "médecin",
  "médecin (1)",
  "médicament",
  "mémoire, thèse",
  "méthode",
  "métier",
  "nager",
  "Nancy",
  "Nantes",
  "nationalité",
  "naturel",
  "neurologique",
  "neutre",
  "neveu",
  "niveau",
  "nièce",
  "noir",
  "nombreux",
  "non (2)",
  "non merci",
  "non-signé",
  "normal",
  "Norvège",
  "notaire",
  "nourriture",
  "nous",
  "nouvelle",
  "nuage",
  "nucléaire",
  "Nîmes",
  "objectif",
  "objection",
  "objet",
  "obligation",
  "observateur",
  "oeuf",
  "officiel",
  "offrir",
  "oie",
  "oncle",
  "oppression",
  "or",
  "oral",
  "orange",
  "organiser",
  "orientation",
  "origine",
  "Orléans",
  "oublier",
  "oui",
  "oumanie (?)",
  "ours",
  "outil",
  "ouvert",
  "où ?",
  "paella",
  "pain (1)",
  "palme",
  "pantalon",
  "papa",
  "papier",
  "paramètre(s)",
  "pardon",
  "pareil",
  "parent (1)",
  "paris",
  "Paris",
  "Paris (1)",
  "parlé",
  "participer",
  "partir",
  "pas compris",
  "pas content",
  "pas d'accord",
  "pas grave",
  "pas la peine",
  "patin à glace",
  "patin à roulettes",
  "patron",
  "pause",
  "payer",
  "perdre",
  "personne (1)",
  "petit (2)",
  "petit-fils",
  "petite-fille",
  "petits-enfants",
  "petit·e-ami·e",
  "peur",
  "pharmacie",
  "philosophe",
  "photo",
  "photocopie",
  "photographie",
  "phrase",
  "physique",
  "ping-pong",
  "pique-nique",
  "piscine",
  "plage",
  "planche à voile",
  "planète",
  "plastique",
  "pleurer",
  "pleuvoir",
  "plombier",
  "plonger",
  "plusieurs",
  "poisson",
  "Poitiers",
  "politique",
  "polonais (langue)",
  "pomme (1)",
  "pomme de terre",
  "pompier",
  "pont",
  "portable",
  "porte (1)",
  "positif",
  "poubelle",
  "poule",
  "pour (3)",
  "pour rien",
  "pourquoi (1)",
  "pourquoi ?",
  "pouvoir",
  "poème",
  "première",
  "prendre",
  "printemps",
  "privé",
  "problème",
  "production",
  "programme",
  "promenade",
  "pronom",
  "proposer",
  "proposition",
  "protéger",
  "préférer",
  "préféré·e",
  "prénom",
  "présenter, montrer",
  "président de la république",
  "prêt",
  "prêter",
  "psychologue",
  "pull (vêtement)",
  "pâques",
  "pâte",
  "pédagogie",
  "pédophile",
  "quand ?",
  "qui ?",
  "quoi ?",
  "raconter",
  "radioactif",
  "ranger",
  "rat",
  "recherche",
  "refuser",
  "regarder",
  "Reims",
  "rejoindre",
  "relation",
  "rembourser",
  "rencontrer",
  "rendez-vous",
  "Rennes",
  "responsable",
  "restaurant",
  "restauration",
  "rester",
  "retard",
  "rire",
  "rival",
  "rivière",
  "riz",
  "robe",
  "roi",
  "roller",
  "Rome",
  "rose",
  "rouge",
  "rouler",
  "Roumanie",
  "route nationale",
  "roux",
  "répondre",
  "réseau (1)",
  "réseau local",
  "réveur",
  "réviser",
  "révision",
  "rôle",
  "s'allier",
  "s'asseoir",
  "s'il vous plait",
  "sac à main",
  "Saint-Étienne",
  "saison (de l'année)",
  "saisons (de l'année)",
  "salade",
  "salle",
  "sandwich",
  "sans interruption",
  "santé",
  "saucisson",
  "sauf",
  "scanner médical",
  "schizophrène",
  "sculpture",
  "se faufiler",
  "se lever",
  "se moquer",
  "se promener",
  "se rappeler",
  "se réveiller",
  "se taire",
  "secrétariat",
  "sens (direction)",
  "serré",
  "seul·e",
  "short (vêtement)",
  "signaire (vocabulaire LSF)",
  "signé (1)",
  "silence",
  "ski",
  "snowboard",
  "social",
  "soeur",
  "soigner",
  "soigner (1)",
  "soir",
  "soldat",
  "soleil",
  "son, sa, ses, leurs",
  "sortie",
  "soucoupe volante",
  "sourd",
  "sourire",
  "souris (1)",
  "sous-marin",
  "sous-titrage",
  "souvent",
  "sport",
  "stage",
  "stagiaire",
  "statut social",
  "Strasbourg",
  "subvention",
  "sucre",
  "suivre",
  "super",
  "surveiller",
  "Suède",
  "symbole",
  "sympathie",
  "sympathique",
  "syndicat",
  "ségrégation",
  "séisme",
  "sélection",
  "t-shirt",
  "table",
  "tableau",
  "tabou",
  "tachycardie",
  "taille (mesure)",
  "talon",
  "tante",
  "tard",
  "tarif",
  "tartine",
  "taureau",
  "taxe",
  "technique",
  "tennis",
  "terminer",
  "terre (1)",
  "terre (3)",
  "terrible",
  "TGV",
  "thermometre",
  "thème",
  "thé",
  "théatre",
  "théorie",
  "théâtre",
  "timbre",
  "toi",
  "tomate",
  "tomber",
  "ton, ta, tes",
  "tortue de mer",
  "tortue de terre",
  "toujours",
  "Toulouse",
  "tourisme",
  "tours",
  "tous les quinze jours",
  "tout (2)",
  "tout le monde",
  "toute la nuit",
  "toxique",
  "train",
  "trajectoire",
  "transport",
  "travailler",
  "tremblement de terre",
  "trimestre",
  "triste",
  "trophée",
  "typique",
  "télécommunication",
  "téléphone",
  "téléphoner",
  "télévision",
  "télévision (1)",
  "tôt",
  "URSS",
  "usine",
  "usine (1)",
  "vacances",
  "vaccination",
  "vache",
  "vaincre",
  "vallée",
  "vanité",
  "veau",
  "vendre",
  "venir (1)",
  "vent (1)",
  "verbe directionnel",
  "verglas",
  "verre de terre",
  "vert",
  "vibration",
  "victoire",
  "vieu",
  "village",
  "ville",
  "ville (2)",
  "violet",
  "virus",
  "visite",
  "visuel",
  "Vitrolle",
  "vocabulaire (1)",
  "voir",
  "voisin",
  "voiture (2)",
  "voler",
  "vous (2)",
  "vélo",
  "vêtement (3)",
  "week-end",
  "zoo",
  "zoo (1)",
  "à bientôt",
  "à genoux",
  "à la saint glinglin",
  "à peu près",
  "à tout à l'heure",
  "âme",
  "ça va",
  "ébéniste",
  "échange",
  "échelon",
  "éclairage",
  "éclipse",
  "école",
  "école (2)",
  "école maternelle",
  "économie",
  "Écosse",
  "écouter",
  "écrire",
  "édifice",
  "éducateur",
  "éducateur (1)",
  "Égypte",
  "électricité",
  "électronique",
  "électrotechnique",
  "élève",
  "élégance",
  "éphémère",
  "épilepsie",
  "équilibre",
  "équipe",
  "État, pays",
  "États-Unis",
  "étonner",
  "étranger",
  "étudiant",
  "été",
  "évolution",
  "être contre",
  "… ou …"
] as const;
